# fly.toml file generated for univ-29 on 2023-04-17T14:19:48+09:00

app = "univ-29"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
