# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 289638d5a69fe7579d0352069c4a9b3413d0ef8b383014ea4cb8c6da74de6637e5732e9ca751e731f2d383dbaf88df55003ff2ffb78c963ec0e91e3e92185b3b

test:
  secret_key_base: ff34562c0faf8925e7695aa29281b3b24800d90c4dbe78fe1eb722a61011fb4f4991cb5742c89c46da88ee1fb9c151325266fee936ad636986bc79baa69a61a0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
